version: "3.2"
services:
  tennismatchsimulator-console:
    build:
      context: .
      dockerfile: src/Api/ConsoleApp/Dockerfile
    ports:
      - 5000:80    
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
